# Generated by Django 3.2.4 on 2021-06-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EligibleTreatment',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'EligibleTreatment',
                'verbose_name_plural': 'EligibleTreatments',
            },
        ),
        migrations.CreateModel(
            name='AssistanceProgram',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=0)),
                ('grant_amount', models.IntegerField()),
                ('url', models.CharField(max_length=255)),
                ('treatments', models.ManyToManyField(related_name='programs', to='AssistanceProgramsWatcher.EligibleTreatment')),
            ],
            options={
                'verbose_name': 'AssistanceProgram',
                'verbose_name_plural': 'AssistancePrograms',
            },
        ),
    ]
